[project]
name = "delete-aae"
version = "1.0.0"
description = "A simple script to delete .AAE files recursively"
authors = [{ name = "Pieterjan Vandenweghe" }]
requires-python = ">=3.11"

[project.scripts]
delete-aae = "delete_aae.main:main"
